config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings do
    resources :reviews, only: [:create, :new]
  end
  resources :cars, except: :index do
    resources :bookings, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  has_one :review
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_many_attached :photos
  validates :model, presence: true
  validates :brand, presence: true
  validates :price, presence: true
  validates :address, presence: true

   geocoded_by :address
   after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_model_and_address,
    against: [ :model, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :booking, uniqueness: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
  has_many :booked_cars, through: :cars, source: :bookings
  # booked_cars is a name we give to an association
  # user through car table looks for bookings using source
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    #How to add first name & last name column// felix created name

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :set_booking, only: [:show, :edit, :destroy, :update]

    def index
        # where allows you to search for all booking(s)
        # you have boooked
        @my_bookings = current_user.bookings
        @bookings = current_user.booked_cars
        # Other people booked
    end

    def create
      @booking = Booking.new()
      # @booking.user_id = current_user.id
      @booking.starts_at = params[:booking][:starts_at]  #how to implement this with strong params
      @booking.ends_at = params[:booking][:ends_at]
      @booking.user = current_user
      @booking.confirmed = nil
      @booking.car_id = params[:car_id] # did not return anyhting null
      if @booking.save
        redirect_to bookings_path  # we dont create a form when press book btn/ alert instead.
      end
    end

    def update
        if params[:confirmed] == "true" #Hidden field tag exaplined
            @booking.confirmed = true
        else
            @booking.confirmed = false
        end
        redirect_to bookings_path
        # @booking = Booking.new(booking_params)
    end
    # @booking

    def destroy
        @booking.destroy 
        redirect_to bookings_path
    end

    def edit
#       @car = Car.where(id: @booking.car_id).first #Could use .find too
#       @client = User.where(id: @booking.car_id).first
        @car = Car.find(@booking.car_id)
        @client = User.find(@booking.user_id)
    end

    def show
        @car = Car.find(@booking.car_id)
        @owner = User.find(@car.user_id)
    end

    private

    def booking_params
        params.require(:bookings).permit(:starts_at, :ends_at)
    end

    def set_booking
        @booking = Booking.find(params[:id])
    end

end
# join table- when you do this explain to us!

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :destroy]
  # skip_before_action :authenticate_user!, only: :search, show

  def index
    @cars = Car.all
  end

  def show
    @booking = Booking.new()
    # @review = Review.new(list: @list)
    # @reviews = Review.where(list_id: list_id)
    @owner = User.find(@car.user_id)
    @marker = {
        lat: @car.latitude,
        lng: @car.longitude
      }
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to root_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to root_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:model, :brand, :price, :address, photos:[])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    #@cars = Car.all no need as we have it below if query is not present
    if params[:query].present?
      @cars = Car.search_by_model_and_address(params[:query])
    else
      @cars = Car.all
    end
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
    end
  end
end

#car.all on line 10 to display all cars rather than the search.

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1 class="text-center mt-3" style="color: #5353b9;">Booking</h1>
<div class="container mt-5">
    <div class="bakground-card-white">
        <div class="infos-client d-flex justify-content-between align-items-center">
            <div class="infos-text">
                <%= link_to "Back", bookings_path, class:"btn btn-outline-primary mb-4" %>
                <h4>Date of rent: <%= @booking.starts_at %> / <%= @booking.ends_at %></h4>
                <p><%= @client.email %></p>
            </div>
            <div class="img-booking-edit">
                <% if @client.photo.attached? %>
                    <%= cl_image_tag @client.photo.key, height: 150, width: 150, crop: :fill, style:"border-radius: 50%;" %>
                <% else %>
                    <img src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" alt="" width="400" height="300">
                <% end %>
            </div>
        </div>
        <hr>
        <div class="car-infos d-flex justify-content-between align-items-center">
            <div>
                <h3>Car Model: <%= @car.model.upcase %></h3>
                <h5>Car Brand: <%= @car.brand.capitalize %></h5>
            </div>
            <% if @car.photos.attached? %>
                <%= cl_image_tag @car.photos.first.key, height: 400, width: 500, crop: :fill %>
            <% end %>
        </div>
        <h4 class="mt-3">Change status of rent</h4>
        <div class="btn-changes d-flex justify-content-begin align-items-center">
            <button type="button" class="btn btn-primary mr-4" data-toggle="modal" data-target="#myModal">Accept Booking</button>
            <%= simple_form_for (@booking) do |f| %>
                <%= hidden_field_tag :confirmed, "false" %>
                <%= f.submit "Deny Booking", class: "btn btn-outline-primary"%>
            <% end %>
        </div>
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Are you sure?</h4>
                    </div>
                    <div class="modal-body">
                        <p>This means that you'll be renting the <%= @car.brand %> to <%= @client.email %></p>
                    </div>
                    <div class="modal-footer">
                        <%= simple_form_for (@booking) do |f| %>
                            <%= hidden_field_tag :confirmed, "true" %>
                            <%= f.submit "Agree", class: "btn btn-outline-primary mr-5"%>
                        <% end %>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" >Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%# <%= link_to "Accept", booking_path(@booking, confirmed: true), method: :patch %>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center mt-3 title-bookings" style="color: #5353b9;">Review your bookings</h1>
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center">
        <h2 class="mt-1 title-bookings" id="title-bookings-show">Your cars</h2>
        <%= link_to "Back", root_path, class:"btn btn-info-car-small" %>
    </div>
    <hr>
    <div class="bakground-card-purple">
        <div class="cards-bookings">
            <% @bookings.each do |booking| %>
                <% car = Car.find(booking.car_id) %>
                <div class="card car-bookings-index" data-aos="fade-right" style="width: 16rem;">
                    <% if car.photos.attached? %>
                        <%= cl_image_tag car.photos.first.key, class: "card-img-top", width: 300, height: 300, crop: :thumb %>
                    <% else %>
                        <%= image_tag "default.jpg", class:"default" %>
                    <% end %>
                    <div class="card-body">
                        <h5 class="card-title"><%= car.brand.upcase %></h5>
                        <p class="card-text" style="margin-bottom: 0px;"><%= car.model.capitalize %></p>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-center">
                        <%= link_to "Infos", edit_booking_path(booking.id), class: "btn btn-info-car" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <h2 class="mt-1 title-bookings mt-5">Your bookings</h2>
    <hr>
    <div class="bakground-card-purple-dark mt-4">
        <div class="cards-bookings">
            <% @my_bookings.each do |booking| %>
                <% car = Car.find(booking.car_id) %>
                <div class="card car-bookings-index" data-aos="fade-right" style="width: 16rem;">
                    <% if car.photos.attached? %>
                        <%= cl_image_tag car.photos.first.key, class: "card-img-top", width: 300, height: 300, crop: :thumb %>
                    <% else %>
                        <%= image_tag "default.jpg", class:"default" %>
                    <% end %>
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h5>Status:</h5>
                            <% if booking.confirmed %>
                                <h5 class="card-title card-info-status">Confirmed</h5>
                            <% elsif booking.confirmed == nil %>
                                <h5 class="card-title card-info-status">Pending</h5>
                            <% else %>
                                <h5 class="card-title card-info-status">Refused</h5>
                            <% end %>
                        </div>
                        <p class="card-text"><%= car.model.upcase %></p>
                        <p class="card-text"><%= car.brand.capitalize %></p>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-around align-items-center mb-3">
                        <%= link_to "Infos", booking_path(booking.id), class: "btn btn-info-car", style:"margin-bottom: 0px"%>
                        <% if booking.confirmed == false %>
                            <%= link_to "Delete", booking_path(booking.id), class: "btn btn-outline-danger", method: :delete, style: "height: 50px;" %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="top-button d-flex justify-content-center" width="100%">
        <button class="btn-chevronUp mt-5" id="btn-goUp-bookings"><i class="fas fa-chevron-circle-up"></i></button>
    </div>
</div>
<!-- what is the (1) meant to represent/ID becuase we dont have bookings working -->

app/views/bookings/show.html.erb
<h1 class="text-center mt-3" style="color: #5353b9;">Your booking</h1>
<div class="container mt-5">
    <% if @booking.confirmed %>
        <h4>Your booking has been confirmed, we hope you'll enjoy the ride! </h4>
    <% elsif @booking.confirmed == nil %>
        <h4>Your booking is currently pending, you'll have to wait a bit..</h4>
    <% else %>
        <h4>Your booking has been denied, we're sorry that it hasn't gone through</h4>
    <% end %>
    <div class="car-infos mt-5">
        <div class="card p-2" style="width: 25rem; box-shadow: 0 10px 15px rgba(0,0,0,0.2);">
            <div class="card-body">
                <h4 class="card-title">Car's info</h4>
                <hr>
                <p class="card-text"><p><%= @car.model.upcase %></p>
                <p class="card-text"><p><%= @car.brand.capitalize %></p></p>
                <p class="card-text"><p>From : <%= @booking.starts_at %> <br> To: <%= @booking.ends_at %></p></p>
                <p style="color: #5353b9;">Owner email address: <br> <%= @owner.email %></p>
                <% days = (@booking.ends_at[-2..]).to_i - (@booking.starts_at[-2..]).to_i %>
                <% price = days * @car.price %>
                <p class="card-text" style="font-weight: 700;">Total price: £<%= price %> </p>
            </div>
        </div>
        <div class="car-photos">
            <div class="card" id="default-img-booking" style="width: 18rem;">
                <% if @car.photos.attached? %>
                    <%= cl_image_tag @car.photos.first.key, class:"d-block w-100", height: 300, width: 400, crop: :fill, id: "default-img-booking-show", data: { zoom: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" }  %>
                <% end %>
            </div>
            <div class="d-flex justify-content-begin align-items-center mt-2">
                <button type="button" class="enable-zoom-button btn btn-primary mr-3 sm">Zoom</button>
                <button type="button" class="disable-zoom-button btn btn-outline-primary sm">Disable</button>
            </div>
        </div>
    </div>
    <% if @booking.confirmed %>
        <div class="Review button">
            <%= link_to "Add a review to your booking", new_booking_review_path(@booking, @review), class:"btn btn-info-car my-5" %>
        </div>
    <% end %>
    <%= link_to "Back", bookings_path, class:"btn btn-outline-primary mt-3" %>
</div>

app/views/cars/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="title-bookings">Edit your New Car:</h2>
      <%= simple_form_for(@car) do |f| %>
        <%= f.input :model %>
        <%= f.input :brand %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :photo, as: :file, input_html: {multiple: true} %>
        <%= f.submit class: 'btn btn-info-car' %>
      <% end %>
    </div>
  </div>
</div>

<!-- add column-->

app/views/cars/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="title-bookings border-bottom mb-4">Add a New Car:</h2>
      <%= simple_form_for(@car) do |f| %>
        <%= f.input :model %>
        <%= f.input :brand %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :photos, as: :file, input_html: {multiple: true} %>
        <%= f.submit class: 'btn btn-info-car' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h1 class="title-bookings mt-3 border-bottom" style="color: #5353b9;">Owner & Car details</h1>
  <div class="row mt-5">

<!-------------------Card 1 Map & Owner Info ------------->

    <div class="col-12 col-lg-6">
      <div class="card-owner d-flex align-items-center justify-content-around"> 

        <div id="map"

           data-markers="<%= @marker.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

        <div class="card-owner-body mt-5 mr-4">
          <h2>Owner info</h2>
          <p><%= @owner.name %></p>
          <p><%= @owner.email %></p>
          <svg style="width: 24px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 20 20" xml:space="preserve"><title>send 2</title><g class="nc-icon-wrapper" fill="#111111"><g transform="translate(2 2)"><path fill="#111111" d="M15.707,0.293c-0.273-0.272-0.68-0.365-1.043-0.234l-14,5C0.287,5.193,0.026,5.54,0.002,5.939 c-0.024,0.4,0.192,0.775,0.551,0.955l4.586,2.292L11,5l-4.187,5.862l2.292,4.586C9.276,15.787,9.623,16,10,16 c0.021,0,0.041-0.001,0.061-0.002c0.4-0.024,0.747-0.284,0.882-0.662l5-14C16.072,0.973,15.98,0.566,15.707,0.293z"/></g></g></svg>
        </div>
      </div>
    </div>

<!------------------End Card 1 Map & Owner Info ------------->
<!------------------Card 2 Carousel------------------------->

    <div class="col-12 col-lg-6">
      <div class="card-client bg-light">
        <div class="mt-3 carousel slide" data-ride="carousel">
         <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
           <ol class="carousel-indicators">
             <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
             <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
             <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
             <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
           </ol>
           <div class="carousel-inner">
              <% if @car.photos.attached? %>
                <% @car.photos.each_with_index do |slide, i| %>
                  <div class="carousel-item <%= 'active' if i == 0 %>">
                      <%= cl_image_tag slide.key, height: 175, width: 300, crop: :pad, class:"d-block w-100"%>
                  </div>
                <% end %>
              <% else %>
                <div class="d-flex justify-content-center">
                  <%#= image_tag "default", height: 180, width: 'auto', class:"d-block" %>
                </div>
              <% end %>
           </div>
           <hr>
           <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
             <span class="carousel-control-prev-icon" aria-hidden="true"></span>
             <span class="sr-only">Previous</span>
           </a>
           <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
             <span class="carousel-control-next-icon" aria-hidden="true"></span>
             <span class="sr-only">Next</span>
           </a>
         </div>
        </div>
        <div class="card-client-body">
          <div class="card-client-body-info">
            <h2 class="card-title"><%= @car.brand %></h2>
            <p class="card-text"><%= @car.model %></p>
          </div>
          <h2 class="card-text"><%= @car.price %>£/day</h2>
        </div>
      </div>
    </div>
  </div>

  <h1 class="title-bookings mt-5 border-bottom" style="color: #5353b9;">Bookings & Reviews</h1>

<!------------------Card 2 Carousel------------------------->
<!--   <div class="map-container">
    <div id="map"
       style="width: 50%; height: 300px;"
       data-markers="<%= @marker.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div> -->

<!----------------------Book Bttn Card------------------------------->

  <div class="d-flex justify-content-between">

  <div class="d-flex justify-content-center mt-3 mr-3">
   <div class="bg-white rounded p-3" style="width: 380px; height: 260px;">
     <div class="d-flex justify-content-between mx-5">
      <% if @owner != current_user %>
         <%= simple_form_for [@car, @booking] do |f| %>
           <%= hidden_field_tag :car_id, @car.id %>
           <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
           <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
           <div class="d-flex justify-content-between">
              <%= f.submit 'book', class:'btn btn-primary' %>
              <%= link_to 'back' , root_path, class:'btn btn-outline-primary ' %>
           </div>
         <% end %>
       <% end %>
     </div>
   </div>
  </div>


<!---------------------End----Book Bttn Card------------------------------->

  <% unless @car.bookings.empty? %>
    <div class="row ml-3">
      <% @car.bookings.each do |booking| %>
        <% unless booking.review.nil? %>
          <div class="col-12 mt-3">
            <div class="card w-95">
              <div class="row">
                <div class="card-body">
                    <h5 class="card-title ; col-10">
                      <% booking.review.rating.times do %>
                      <i class="fas fa-star" style="color:#5353b9 !important;"></i>
                      <% end %>
                      <% empty_stars = 5 - booking.review.rating %>
                      <% empty_stars.times do %>
                      <i class="far fa-star" style="color:#5353b9 !important;"></i>
                      <% end %>
                    </h5>
                    <p class="card-text pl-3"><%= booking.review.content %></p>
                </div>
                <div class="col-2 mt-3 pr-4">
                  <% user = User.find(booking.user_id) %>
                  <% if user.photo.attached? %>
                    <%= cl_image_tag user.photo.key, height: 60, width: 60, crop: :fill, class:"avatar-large" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  </div>

app/views/pages/home.html.erb
<div class="bg-white">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526550517342-e086b387edda?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2901&q=80)">
    <div class="info-banner">
      <h1>Welcome to Car2Me</h1>
      <h4>We're happy to have you around</h4>
      <p><span id="typed-strings"></span></p>
      <% if !user_signed_in? %>
        <%= link_to 'Sign in' , new_user_session_path, class:'btn btn-primary', id:'btn-signup' %>
      <% end %>
    </div>
  </div>
</div>
<!-----------------------------End--Banner------------------------------------>
<div class="home-page-container">
<!---------------------------Search and Add------------------------------------->
  <div class="d-flex justify-content-between align-items-center  my-4">
    <%= link_to 'Add a car' , new_car_path, class:'btn btn-primary' %>
    <div class="search-car">
      <!-- going to root path using action / -->
      <form class="d-flex justify-content-between" method="GET" action='/'>
        <div class="pr-4">
          <input type="text" placeholder="Search car.." class="btn-search-grey form-control mr-2" style="width: 12.5rem" name='query'>
        </div>
        <div>
          <input type="submit" name="search" class='btn btn-outline-primary'>
        </div>
      </form>
    </div>
  </div>
<!-----------------------------------End-Search and Add------------------------------------->
<!----------------------------------Cards && Map ----------------------------------->
  <div class="main-container">
    <div class="background-card-purple-2">
      <% @cars.each do |car| %>
      <div class="card-home-page" data-aos="fade-up">
        <% if car.photos.attached? %>
        <%= cl_image_tag car.photos.first.key, class:'card-img-top mb-2', height: 150, crop: :fill %>
        <% else %>
        <%= image_tag "default.jpg", class:'default card-img-top mb-2'%>
        <% end %>
        <!-- <img src="https://images.unsplash.com/photo-1494976388531-d1058494cdd8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" class="card-img-top" alt="..."> -->
        <div class="card-body">
          <h5 class="card-title"><%= car.brand %></h5>
          <p class="card-text"><%= car.model %></p>
          <p class="card-text">£<%= car.price %>/day</p>
          <div class="btn-spacing">
            <%= link_to "Details", car_path(car), class:'btn-info-car-small' %>
            <% if current_user %>
            <!-- if true current user is logged in-->
            <% if car.user_id == current_user.id %>
            <!-- car.user == current_user -->
            <!-- if statment to make sure you only effect change on users cars- visually access to editting/delete -->
            <%= link_to "Edit", edit_car_path(car), class:'btn btn-outline-warning mx-1'%>
            <%= link_to "Delete", car_path(car), method: :delete, data: { confirm: "U-sure?" }, class:'btn btn-outline-danger' %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
<!----------------------------------------End-Cards---------------------------------------------->
    <div id="map-2" class="map"
       style="height: 80vh;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <!---------------------------------End-Cards && Map ----------------------------------->
<!---------------------------------UP Chevron------------------------------------------>
  <div class="top-button d-flex justify-content-center" width="100%">
    <button class="btn-chevronUp mt-5" id="btn-goUp-home"><i class="fas fa-chevron-circle-up"></i></button>
  </div>
<!---------------------------------End-UP Chevron ----------------------------------->
</div>
<!---------------------------------End of Container ----------------------------------->

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
    <% if user_signed_in? %>
      <div class="d-flex justify-content-between align-items-center" width="100px">
          <%= link_to "Home", root_path, class: "nav-link" %>
        <div class="d-flex align-items-center">
          <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          <div class="nav-item dropdown">

            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", style:"object-fit: cover", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" class="avatar dropdown-toggle" style="object-fit: cover" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% end %>
            <div class="dropdown-menu dropdown-menu-right nav-item-link" aria-labelledby="navbarDropdown">
              <%= link_to "Add a car", new_car_path, class: "dropdown-item" %>
              <%= link_to "Edit my profile", edit_user_registration_path, class:"dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
  </ul>
</div>